### Listar produtos
GET http://localhost:3000/produto

### Buscar produto por nome
GET http://localhost:3000/produto/1

### Cadastrar produtos
POST http://localhost:3000/produto
Content-Type: application/json

{
    "nome": "Produto Teste3",
    "preco": 3.3
}

### Deletar produtos
DELETE http://localhost:3000/produto/2

### Atualizar produtos
PUT http://localhost:3000/produto
Content-Type: application/json

{
    "id": 3,
    "nome": "Produto Teste3",
    "preco": 3.3
}